# generated by datamodel-codegen:
#   filename:  events.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Stage(StrEnum):
    ingestion = 'ingestion'
    index = 'index'
    scan = 'scan'
    route = 'route'
    queue = 'queue'
    worker = 'worker'
    validate = 'validate'


class ProgressEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Literal['progress']
    session_id: str
    stage: Stage
    pct: Annotated[float | None, Field(description='Fortschritt in Prozent, optional', ge=0.0, le=100.0)] = None
    message: str | None = None


class Severity(StrEnum):
    info = 'info'
    warning = 'warning'
    error = 'error'
    critical = 'critical'


class FindingEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Literal['finding']
    session_id: str
    scope: str
    severity: Severity
    message: str


class PartialEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Literal['partial']
    session_id: str
    fragment: Annotated[str, Field(description='Streaming-Fragment eines LLM-Workers')]


class ArtifactType(StrEnum):
    symbol_index = 'symbol_index'
    dependency_graph = 'dependency_graph'
    call_graph = 'call_graph'
    code_summary = 'code_summary'
    code_explanation = 'code_explanation'
    review_findings = 'review_findings'
    refactor_plan = 'refactor_plan'
    debug_analysis = 'debug_analysis'
    test_generation = 'test_generation'
    docstring = 'docstring'
    plan = 'plan'
    patch = 'patch'
    lint_report = 'lint_report'


class ProducerClass(StrEnum):
    det = 'det'
    prob = 'prob'


class ResultEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Literal['result']
    session_id: str
    artifact_type: ArtifactType
    scope: str
    producer_class: ProducerClass


class ErrorEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Literal['error']
    session_id: str
    code: str
    message: str


class Event(RootModel[ProgressEvent | FindingEvent | PartialEvent | ResultEvent | ErrorEvent]):
    root: Annotated[ProgressEvent | FindingEvent | PartialEvent | ResultEvent | ErrorEvent, Field(description='Wire-Format fuer alle Ereignisse vom Kern an Frontends (JSON-Lines). Das t-Feld ist der Diskriminator. Go-CLI liest nur t und Rendering-Felder.', title='Event')]
