# generated by datamodel-codegen:
#   filename:  provenance.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ProducerClass(StrEnum):
    det = 'det'
    prob = 'prob'


class ArtifactType(StrEnum):
    symbol_index = 'symbol_index'
    dependency_graph = 'dependency_graph'
    call_graph = 'call_graph'
    code_summary = 'code_summary'
    code_explanation = 'code_explanation'
    review_findings = 'review_findings'
    refactor_plan = 'refactor_plan'
    debug_analysis = 'debug_analysis'
    test_generation = 'test_generation'
    docstring = 'docstring'
    plan = 'plan'
    patch = 'patch'
    verify_report = 'verify_report'


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Annotated[str, Field(description='Schema-Version fuer Interpretierbarkeit alter Artefakte')]
    source_hash: Annotated[str, Field(description='commit_hash oder worktree_hash des Quell-Repo')]
    input_hash: Annotated[str, Field(description='Content-Hash der Eingabe (Staleness-Lookup)')]
    producer: Annotated[str, Field(description='Bezeichner des Erzeugers, z.B. tree-sitter-py oder qwen2.5-coder')]
    producer_version: Annotated[str, Field(description='Tool- oder Modellversion')]
    producer_class: Annotated[ProducerClass, Field(description='det = deterministisch, prob = probabilistisch (LLM)')]
    timestamp: Annotated[AwareDatetime, Field(description='Erzeugungszeit (ISO 8601 mit Zeitzone)')]
    artifact_type: Annotated[ArtifactType, Field(description='Typ des Artefakts. Geschlossene Enum ueber S1-S5, vorgebaut.')]
    scope: Annotated[str, Field(description='Scope-Schluessel: [repo-id::]typ:pfad[#symbolpfad[/arity]]', pattern='^([A-Za-z0-9_.-]+::)?(repo|file|module|symbol):[^#]*(#[A-Za-z0-9_.]+(/[0-9]+)?)?$')]
