// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

type ErrorEvent struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message" yaml:"message" mapstructure:"message"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`

	// T corresponds to the JSON schema field "t".
	T string `json:"t" yaml:"t" mapstructure:"t"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in ErrorEvent: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in ErrorEvent: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in ErrorEvent: required")
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in ErrorEvent: required")
	}
	type Plain ErrorEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.T != "error" {
		return fmt.Errorf("field %s: must be equal to %s", "t", "error")
	}
	*j = ErrorEvent(plain)
	return nil
}

type FindingEvent struct {
	// Message corresponds to the JSON schema field "message".
	Message string `json:"message" yaml:"message" mapstructure:"message"`

	// Scope corresponds to the JSON schema field "scope".
	Scope string `json:"scope" yaml:"scope" mapstructure:"scope"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`

	// Severity corresponds to the JSON schema field "severity".
	Severity FindingEventSeverity `json:"severity" yaml:"severity" mapstructure:"severity"`

	// T corresponds to the JSON schema field "t".
	T string `json:"t" yaml:"t" mapstructure:"t"`
}

type FindingEventSeverity string

const FindingEventSeverityCritical FindingEventSeverity = "critical"
const FindingEventSeverityError FindingEventSeverity = "error"
const FindingEventSeverityInfo FindingEventSeverity = "info"
const FindingEventSeverityWarning FindingEventSeverity = "warning"

var enumValues_FindingEventSeverity = []interface{}{
	"info",
	"warning",
	"error",
	"critical",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FindingEventSeverity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FindingEventSeverity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FindingEventSeverity, v)
	}
	*j = FindingEventSeverity(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FindingEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in FindingEvent: required")
	}
	if _, ok := raw["scope"]; raw != nil && !ok {
		return fmt.Errorf("field scope in FindingEvent: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in FindingEvent: required")
	}
	if _, ok := raw["severity"]; raw != nil && !ok {
		return fmt.Errorf("field severity in FindingEvent: required")
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in FindingEvent: required")
	}
	type Plain FindingEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.T != "finding" {
		return fmt.Errorf("field %s: must be equal to %s", "t", "finding")
	}
	*j = FindingEvent(plain)
	return nil
}

type PartialEvent struct {
	// Streaming-Fragment eines LLM-Workers
	Fragment string `json:"fragment" yaml:"fragment" mapstructure:"fragment"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`

	// T corresponds to the JSON schema field "t".
	T string `json:"t" yaml:"t" mapstructure:"t"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PartialEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["fragment"]; raw != nil && !ok {
		return fmt.Errorf("field fragment in PartialEvent: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in PartialEvent: required")
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in PartialEvent: required")
	}
	type Plain PartialEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.T != "partial" {
		return fmt.Errorf("field %s: must be equal to %s", "t", "partial")
	}
	*j = PartialEvent(plain)
	return nil
}

type ProgressEvent struct {
	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Fortschritt in Prozent, optional
	Pct *float64 `json:"pct,omitempty,omitzero" yaml:"pct,omitempty" mapstructure:"pct,omitempty"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`

	// Stage corresponds to the JSON schema field "stage".
	Stage ProgressEventStage `json:"stage" yaml:"stage" mapstructure:"stage"`

	// T corresponds to the JSON schema field "t".
	T string `json:"t" yaml:"t" mapstructure:"t"`
}

type ProgressEventStage string

const ProgressEventStageIndex ProgressEventStage = "index"
const ProgressEventStageIngestion ProgressEventStage = "ingestion"
const ProgressEventStageQueue ProgressEventStage = "queue"
const ProgressEventStageRoute ProgressEventStage = "route"
const ProgressEventStageScan ProgressEventStage = "scan"
const ProgressEventStageValidate ProgressEventStage = "validate"
const ProgressEventStageWorker ProgressEventStage = "worker"

var enumValues_ProgressEventStage = []interface{}{
	"ingestion",
	"index",
	"scan",
	"route",
	"queue",
	"worker",
	"validate",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProgressEventStage) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProgressEventStage {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProgressEventStage, v)
	}
	*j = ProgressEventStage(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProgressEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in ProgressEvent: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in ProgressEvent: required")
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in ProgressEvent: required")
	}
	type Plain ProgressEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Pct != nil && 100 < *plain.Pct {
		return fmt.Errorf("field %s: must be <= %v", "pct", 100)
	}
	if plain.Pct != nil && 0 > *plain.Pct {
		return fmt.Errorf("field %s: must be >= %v", "pct", 0)
	}
	if plain.T != "progress" {
		return fmt.Errorf("field %s: must be equal to %s", "t", "progress")
	}
	*j = ProgressEvent(plain)
	return nil
}

type ResultEvent struct {
	// ArtifactType corresponds to the JSON schema field "artifact_type".
	ArtifactType ResultEventArtifactType `json:"artifact_type" yaml:"artifact_type" mapstructure:"artifact_type"`

	// ProducerClass corresponds to the JSON schema field "producer_class".
	ProducerClass ResultEventProducerClass `json:"producer_class" yaml:"producer_class" mapstructure:"producer_class"`

	// Scope corresponds to the JSON schema field "scope".
	Scope string `json:"scope" yaml:"scope" mapstructure:"scope"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`

	// T corresponds to the JSON schema field "t".
	T string `json:"t" yaml:"t" mapstructure:"t"`
}

type ResultEventArtifactType string

const ResultEventArtifactTypeCallGraph ResultEventArtifactType = "call_graph"
const ResultEventArtifactTypeCodeExplanation ResultEventArtifactType = "code_explanation"
const ResultEventArtifactTypeCodeSummary ResultEventArtifactType = "code_summary"
const ResultEventArtifactTypeDebugAnalysis ResultEventArtifactType = "debug_analysis"
const ResultEventArtifactTypeDependencyGraph ResultEventArtifactType = "dependency_graph"
const ResultEventArtifactTypeDocstring ResultEventArtifactType = "docstring"
const ResultEventArtifactTypePatch ResultEventArtifactType = "patch"
const ResultEventArtifactTypePlan ResultEventArtifactType = "plan"
const ResultEventArtifactTypeRefactorPlan ResultEventArtifactType = "refactor_plan"
const ResultEventArtifactTypeReviewFindings ResultEventArtifactType = "review_findings"
const ResultEventArtifactTypeSymbolIndex ResultEventArtifactType = "symbol_index"
const ResultEventArtifactTypeTestGeneration ResultEventArtifactType = "test_generation"
const ResultEventArtifactTypeVerifyReport ResultEventArtifactType = "verify_report"
const ResultEventArtifactTypeDesign ResultEventArtifactType = "design"
const ResultEventArtifactTypeTestReport ResultEventArtifactType = "test_report"

var enumValues_ResultEventArtifactType = []interface{}{
	"symbol_index",
	"dependency_graph",
	"call_graph",
	"code_summary",
	"code_explanation",
	"review_findings",
	"refactor_plan",
	"debug_analysis",
	"test_generation",
	"docstring",
	"plan",
	"patch",
	"verify_report",
	"design",
	"test_report",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResultEventArtifactType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResultEventArtifactType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResultEventArtifactType, v)
	}
	*j = ResultEventArtifactType(v)
	return nil
}

type ResultEventProducerClass string

const ResultEventProducerClassDet ResultEventProducerClass = "det"
const ResultEventProducerClassProb ResultEventProducerClass = "prob"

var enumValues_ResultEventProducerClass = []interface{}{
	"det",
	"prob",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResultEventProducerClass) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResultEventProducerClass {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResultEventProducerClass, v)
	}
	*j = ResultEventProducerClass(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResultEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["artifact_type"]; raw != nil && !ok {
		return fmt.Errorf("field artifact_type in ResultEvent: required")
	}
	if _, ok := raw["producer_class"]; raw != nil && !ok {
		return fmt.Errorf("field producer_class in ResultEvent: required")
	}
	if _, ok := raw["scope"]; raw != nil && !ok {
		return fmt.Errorf("field scope in ResultEvent: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in ResultEvent: required")
	}
	if _, ok := raw["t"]; raw != nil && !ok {
		return fmt.Errorf("field t in ResultEvent: required")
	}
	type Plain ResultEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.T != "result" {
		return fmt.Errorf("field %s: must be equal to %s", "t", "result")
	}
	*j = ResultEvent(plain)
	return nil
}
